---
title: "Untitled"
author: "Stephanie"
date: "2/13/2018"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      eval=FALSE)
```

Load libraries

```{r library}
#Hex grid Victoria
library(sf)
library(rgdal)
library(rmapshaper)
library(tidyverse)
library(ggplot2)
library(ggthemes)
library(ggrepel)
#library(hexmapr)
library(geogrid)
```

Data, download link

```{r data, dependson=c("library")}
# download from web address:

# http://www.ausstats.abs.gov.au/ausstats/subscriber.nsf/0/A09309ACB3FA50B8CA257FED0013D420/$File/1270055001_sa2_2016_aust_shape.zip

SAtwo = readOGR(dsn="./data/SA2_2016_AUST.shp", layer="SA2_2016_AUST")
#dropping null geometries, areas with no residents?

clean <- function(shape, simplify=TRUE) {
  shape@data$id = rownames(shape@data)
  if (simplify) {
  shape <- rmapshaper::ms_simplify(shape, keep=0.01)
  }
  shape.points = fortify(shape, region="id")
  shape.df = merge(shape.points, shape@data, by="id")
}

SAtwo_df <- clean(SAtwo)

polys <- as(SAtwos, "SpatialPolygons")

centroid <- function(i, polys) {
  ctr <- Polygon(polys[i])@labpt
  id <- SAtwo$id[i]
  data.frame(long_c=ctr[1], lat_c=ctr[2], id = id)
}

centroids <- seq_along(polys) %>% purrr::map_df(centroid, polys=polys)

#join the centroids to full data set

SAtwos.df <- full_join(SAtwos.df, centroids)
```

Greater Melbourne Area

```{r}
melb <- SAtwos.df %>% mutate(code = substr(SA2_NAME16, 1, 4)) %>%
  filter(GCC_CODE16=="2GMEL")

ggplot(data=melb) +
  aes(long, lat, group=group, fill = GCC_CODE16) +
  geom_polygon() +
  scale_fill_manual(values = alpha(c("blue"), .02))+
  theme(legend.position = "none") +
  theme(panel.background = element_rect(fill = "transparent", colour = NA), plot.background = element_rect(fill = "transparent", colour = NA)) +
  geom_path(colour="black") + 
  geom_text_repel(data= 
    melb %>%
    group_by(id) %>%
    mutate(x=mean(long), y=mean(lat)) %>%
    distinct(id, .keep_all = TRUE), 
    aes(x=x, y=y,label=code),
    size = 2)
  

ggplot(melb) +
  geom_polygon(aes(x = long, y = lat, group = group)) +
  geom_text(aes(long_c, lat_c, label = code), size = 2,color = "white") +
  coord_equal() +
  guides(fill = FALSE) +
  theme_void()
```



Speed of assign_polygons not adequate

```{r}

# From STAT585, use to extract ploygons?
#rather than using the assign_polygons function
extractPolygons <- function(shapes) {
  require(plyr)

  dframe <- ldply(1:length(shapes@polygons), function(i) {
    ob <- shapes@polygons[[i]]@Polygons
    dframe <- ldply(1:length(ob), function(j) {
      x <- ob[[j]]
      co <- x@coords
      data.frame(co, order = 1:nrow(co), group = j)
    })
    dframe$region <- new_cells[[2]]@polygons[[i]]@plotOrder
    dframe
  })
  # construct a group variable from both group and polygon:
  dframe$group <- interaction(dframe$region, dframe$group)

  dframe
}

expol <- extractPolygons(new_cells[[2]])
#expol$id <- substr(expol$region, 3,6)
expol$region %in% melbSPDF@plotOrder
new_cells.df = left_join(expol, melbSPDF@plotOrder, by=c("region" = "id"))
```



Vic hex map data

```{r}
melbSPDF <- subset(SAtwos, GCC_CODE16=="2GMEL")
vicSPDF <- subset(SAtwos, STE_NAME16=="Victoria")


new_cells <- calculate_grid(shape = melbSPDF, grid_type = "hexagonal", seed = 2017)
# takes too long!
#hexmelb <- assign_polygons(melbSPDF, new_cells)
#save(hexmelb, file="hexmelb.Rdata")


new_vic <- calculate_grid(shape = vicSPDF, grid_type = "hexagonal", seed = 2017)
# takes too long!
#system.time(hexvic <- assign_polygons(vicSPDF, new_vic))
#save(hexmelb, file="hexmelb.Rdata")
```


```{r, fig.height=8}
hexmelb@data$id = rownames(hexmelb@data)
hexmelb.points = fortify(hexmelb, region="id")
hexmelb.df = merge(hexmelb.points, hexmelb@data, by="id")

#SAtwos.points = fortify(SAtwos, region="id")
#SAtwos.df = full_join(SAtwos.points, SAtwos@data, by="id")

ggplot(hexmelb.df) +
  geom_polygon(aes(x = long, y = lat, group = group, fill=factor(SA4_NAME16))) +
  geom_text(aes(V1, V2, label = substr(SA2_NAME16, 1, 4)), size = 3, color = "black") +
  scale_fill_viridis(alpha=0.4, discrete=TRUE) +
  coord_equal() +
  guides(fill = FALSE) +
  theme_void()

```


Plot Victorian SA4's separately 

```{r dependson=data, eval = FALSE}
#Vic only
vicSPDF <- subset(SAtwos, STE_NAME16=="Victoria")


#Vic area names
Y <- vicSPDF %>% split(.@data$SA4_NAME16) %>%
  map_df(., nrow) %>%
  gather(., key = "number", value = "val") %>%
  filter(val>0) %>% select(number)

#Y[17,1]
#individual plot for each
for (i in 1:17) {
#locate a region
vicSPDF %>% subset(.@data$SA4_NAME16 == Y[i,1] %>% pull()) -> warr
#vicSPDF %>% subset(.@data$GCC_CODE16 == "2GMEL") -> warr
#assign polygons to hexagons
ap_warr<- assign_polygons(warr, calculate_grid(shape = warr, learning_rate = 0.01, grid_type = "hexagonal", seed = 4017))
# make dataframe
ap_warr@data$id = rownames(ap_warr@data)
ap_warr.points = fortify(ap_warr, region="id")
ap_warr.df = merge(ap_warr.points, ap_warr@data, by="id")

name<-as.character(Y[i,1] %>% pull())
write_csv(ap_warr.df, paste(name, "4017.csv", sep=""))

plot <- ggplot(ap_warr.df) +
  geom_polygon(aes(x = long, y = lat, group = group, fill=factor(SA4_NAME16))) +
  geom_text(aes(V1, V2, label = substr(SA2_NAME16, 1, 4)), size = 2, color = "black") +
  #scale_fill_viridis(alpha=0.4, discrete=TRUE) +
  coord_equal() +
  guides(fill = FALSE) +
  theme_void()  +
    theme(
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_rect(fill = "transparent",colour = NA),
        plot.background = element_rect(fill = "transparent",colour = NA)
        )

ggsave(paste0(Y[i,1] %>% pull(), "4017.png"), plot, bg = "transparent")
}
```




```{r}
#nm <- as.vector(SAtwos.df$SA4_NAME16) %>% unique()
#melblist <- grep('Melbourne', nm, value=TRUE)

inmelbSPDF <- subset(SAtwo, SA4_NAME16 %in% melblist)

ap_inmelb <- assign_polygons(inmelbSPDF, calculate_grid(shape = inmelbSPDF, learning_rate = 0.001,grid_type = "hexagon", seed = 3017))

ap_inmelb_df <- clean(ap_inmelb, simplify = FALSE)

ggplot(ap_inmelb_df) +
  geom_polygon(aes(x = long, y = lat, group = group, fill=factor(SA4_NAME16))) +
  geom_text(aes(V1, V2, label = substr(SA2_NAME16, 1, 4)), size = 2, color = "black") +
  #scale_fill_viridis(alpha=0.4, discrete=TRUE) +
  coord_equal() +
  guides(fill = FALSE) +
  theme_void()  +
    theme(
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_rect(fill = "transparent",colour = NA),
        plot.background = element_rect(fill = "transparent",colour = NA)
        )
```

Compare new centroid distance from original lat and long

```{r}
library(geosphere)
Ballarat4017 <- read_csv("data/4017/Ballarat4017.csv")

Ballarat4017 %>% distinct(id, .keep_all = TRUE) -> Ballarat4017areas

Ballarat4017areas 

```




