---
title: "Atlas Beginnings"
author: "Stephanie"
date: "22 January 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE)
```

```{r}
library(fiftystater)
library(tidyverse)

incd <- read_csv("../atlas/data/incd.csv",
    skip = 9, n_max = 53, col_names = c(
      "State",
    "FIPS",
    "Objective",
    "IRAgeAdjusted",
    "IRLower95",
    "IRUpper95",
    "AvgAnnualCount",
    "RecentTrend", 
    "RecentTrend5yr", 
    "TrendLower95",
    "TrendUpper95"), na="NA")

incd <- incd %>% mutate(State=gsub("\\s*\\([^\\)]+\\)", "", State)) %>%
     mutate_if(is.double,as.numeric)

# for only 50 states of US
incd %>% filter(tolower(State) %in% fifty_states$id) -> incd50


```



###Choropleth Maps

Choropleth maps of Incidence Rate, Lower 95% Confidence Interval, Upper 95% Confidence Interval.

```{r}
ggplot(incd, aes(map_id = tolower(State))) + 
  # map points to the fifty_states shape data
  geom_map(aes(fill = IRAgeAdjusted), map = fifty_states) + 
  expand_limits(x = fifty_states$long, y = fifty_states$lat) +
  coord_map() +
  scale_x_continuous(breaks = NULL) + 
  scale_y_continuous(breaks = NULL) +
  labs(x = "", y = "") +
  theme(legend.position = "bottom", 
        panel.background = element_blank())
```


```{r}
ggplot(incd, aes(map_id = tolower(State))) + 
  # map points to the fifty_states shape data
  geom_map(aes(fill = IRLower95), map = fifty_states) + 
  expand_limits(x = fifty_states$long, y = fifty_states$lat) +
  coord_map() +
  scale_x_continuous(breaks = NULL) + 
  scale_y_continuous(breaks = NULL) +
  labs(x = "", y = "") +
  theme(legend.position = "bottom", 
        panel.background = element_blank())
```




```{r}
ggplot(incd, aes(map_id = tolower(State))) + 
  # map points to the fifty_states shape data
  geom_map(aes(fill = IRUpper95), map = fifty_states) + 
  expand_limits(x = fifty_states$long, y = fifty_states$lat) +
  coord_map() +
  scale_x_continuous(breaks = NULL) + 
  scale_y_continuous(breaks = NULL) +
  labs(x = "", y = "") +
  theme(legend.position = "bottom", 
        panel.background = element_blank())

```


### Dot plot
```{r, fig.height=7.5}
incd %>% select("State", "IRLower95","IRUpper95") %>% gather(key = "Conf", value = "Value", IRLower95, IRUpper95) -> ConfInts
  
ggplot(incd) + 
  geom_point(aes(y=reorder(State, IRAgeAdjusted), x=IRAgeAdjusted)) + 
  geom_path(data= ConfInts, aes(y=State, group=State, x=Value), col="blue")
  
```


### Hex Map

```{r}
library(rgdal)
library(rgeos)
library(ggplot2)
 
us <- readOGR("us_states_hexgrid.geojson", "OGRGeoJSON")


centers <- cbind.data.frame(data.frame(gCentroid(us, byid=TRUE), id=us@data$iso3166_2))
 
us_map <- fortify(us, region="iso3166_2")

incd50 %>% mutate(google_name = paste0(State, " (United States)")) %>% select(google_name, IRAgeAdjusted) %>% full_join(., us@data) -> hexdata



gg <- ggplot()+ geom_map(data=us_map, map=us_map,
                    aes(x=long, y=lat, map_id=id),
                    color="white", size=0.5)

gg <- gg + geom_map(data=hexdata, map=us_map,
                    aes(fill=IRAgeAdjusted, map_id=iso3166_2))
gg <- gg + geom_map(data=us@data, map=us_map,
                    aes(map_id=iso3166_2),
                    fill="#ffffff", alpha=0, color="white",
                    show_guide=FALSE)

gg <- gg + geom_text(data=centers, aes(label=id, x=x, y=y), color="white", size=4)
gg <- gg + scale_fill_distiller(palette="RdPu", na.value="#7f7f7f")
gg <- gg + coord_map()
gg <- gg + labs(x=NULL, y=NULL)
gg <- gg + theme_bw()
gg <- gg + theme(panel.border=element_blank())
gg <- gg + theme(panel.grid=element_blank())
gg <- gg + theme(axis.ticks=element_blank())
gg <- gg + theme(axis.text=element_blank())
gg

```


