---
title: "All cancers"
author: "Stephanie Kobakian and Di Cook"
date: "5/8/2018"
output: pdf_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, 
                      message=FALSE, 
                      error=FALSE, 
                      warning = FALSE, cache=FALSE,
                      fig.height = 4,
                      fig.width = 6, 
                      fig.align = "centre", 
                      dpi=300, dev ="png")
```



```{r}
# Load libraries and data sets
library(tidyverse)
library(ggthemes)
library(gridExtra)
library(ggpolypath)

# Tidy format spatial polypaths, for easy plotting
load("data/sa2_tidy11.Rda")
# Hex gridded sa2 regions
load("data/sa2_hex11.Rda")
# Cancer SIR data
sa2_info <- read_csv("data/SIR_all_test.csv") %>% mutate(SA2_5DIG11 = as.factor(sa2))
sa2_estimates <- read_csv("data/SIR_all_2014.csv") 

sa2_p50 <- sa2_estimates %>% arrange(desc(cancergrp)) %>% select(SA2_5DIG11 = sa2, cancergrp, males_p50, females_p50, persons_p50) %>%  gather(key = sexname, value = sir_p50, males_p50:persons_p50) %>% mutate(sexname = gsub(pattern = "_p50","", sexname))

sa2_p50w <- sa2_p50 %>% spread(key = cancergrp, value = sir_p50) %>% mutate(SA2_5DIG11=as.factor(SA2_5DIG11))

sa2_sub <- sa2_p50w %>% select(SA2_5DIG11, sexname, `11`, `23`, `27`, `48`) 
```
 

Map of Australian SA2 areas represented by hexagons, coloured by National Cancer Atlas colours.
Data provided by Susanna Cramb and Thom Saunders.


```{r}
nac_colours <- c("A" = "#33809d",
                 "B" = "#aec6c7",
                 "C" = "#fff4bc",
                 "D" = "#ff9a64",
                 "E" = "#ff3500")
```


```{r}
# join hex to chosen cancer data 

cd11 <- left_join(sa2_hex, 
                  select(sa2_sub, SA2_5DIG11, sir_p50 = `11`)) %>% 
  mutate(colrs = case_when(
      sir_p50 < 0.5  ~ "A",
      sir_p50 >= 0.5 & sir_p50 < 1  ~ "B",
      sir_p50 >= 1 & sir_p50 < 1.5  ~ "C",
      sir_p50 >= 1.5 & sir_p50 < 2  ~ "D",
      sir_p50 > 2  ~ "E"))
  
  
ggplot() + geom_polypath(data=sa2_tidy, aes(x=long, y=lat, group=group),
               fill="white", colour="grey90") +
  geom_hex(data=cd11, aes(x = hex_long, y = hex_lat,
               fill = colrs),
           colour = NA, stat = "identity") +
  scale_fill_manual(values = nac_colours) +
  theme_map() + 
  guides(fill=FALSE)
```


```{r}

cd23 <- left_join(sa2_hex, 
                  select(sa2_sub, SA2_5DIG11, sir_p50 = `23`)) %>% 
  mutate(colrs = case_when(
      sir_p50 < 0.5  ~ "A",
      sir_p50 >= 0.5 & sir_p50 < 1  ~ "B",
      sir_p50 >= 1 & sir_p50 < 1.5  ~ "C",
      sir_p50 >= 1.5 & sir_p50 < 2  ~ "D",
      sir_p50 > 2  ~ "E"))
  
  
ggplot() + geom_polypath(data=sa2_tidy, aes(x=long, y=lat, group=group),
               fill="white", colour="grey90") +
  geom_hex(data=cd23, aes(x = hex_long, y = hex_lat,
               fill = colrs),
           colour = NA, stat = "identity") +
  scale_fill_manual(values = nac_colours) +
  theme_map() + 
  guides(fill=FALSE)
```

```{r}

cd27 <- left_join(sa2_hex, 
                  select(sa2_sub, SA2_5DIG11, sir_p50 = `27`)) %>% 
  mutate(colrs = case_when(
      sir_p50 < 0.5  ~ "A",
      sir_p50 >= 0.5 & sir_p50 < 1  ~ "B",
      sir_p50 >= 1 & sir_p50 < 1.5  ~ "C",
      sir_p50 >= 1.5 & sir_p50 < 2  ~ "D",
      sir_p50 > 2  ~ "E"))
  
  
ggplot() + geom_polypath(data=sa2_tidy, aes(x=long, y=lat, group=group),
               fill="white", colour="grey90") +
  geom_hex(data=cd27, aes(x = hex_long, y = hex_lat,
               fill = colrs),
           colour = NA, stat = "identity") +
  scale_fill_manual(values = nac_colours) +
  theme_map() + 
  guides(fill=FALSE)
```


```{r}
cd48 <- left_join(sa2_hex, 
                  select(sa2_sub, SA2_5DIG11, sir_p50 = `48`)) %>% 
  mutate(colrs = case_when(
      sir_p50 < 0.5  ~ "A",
      sir_p50 >= 0.5 & sir_p50 < 1  ~ "B",
      sir_p50 >= 1 & sir_p50 < 1.5  ~ "C",
      sir_p50 >= 1.5 & sir_p50 < 2  ~ "D",
      sir_p50 > 2  ~ "E"))
  
  
ggplot() + geom_polypath(data=sa2_tidy, aes(x=long, y=lat, group=group),
               fill="white", colour="grey90") +
  geom_hex(data=cd48, aes(x = hex_long, y = hex_lat,
               fill = colrs),
           colour = NA, stat = "identity") +
  scale_fill_manual(values = nac_colours) +
  theme_map() + 
  guides(fill=FALSE)

```
