---
title: "Australia Maps"
author: "Stephanie Kobakian and Di Cook"
date: "4/13/2018"
output: pdf_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
library(ggthemes)
library(gridExtra)
load("data/sa2.Rda")
load("data/sa2_tidy.Rda")
load("data/sa2_hex.Rda")
```
 

```{r}
p1 <- ggplot(sa2_hex, aes(x=long, y=hex_long, colour=rank(desc(pop)))) +
  scale_colour_gradient(low="#c0c030", high="#607848") +
  geom_abline(slope=1, intercept=0) + geom_point(alpha=0.1) +
  theme(aspect.ratio=1, legend.position="none")
p2 <- ggplot(sa2_hex, aes(x=lat, y=hex_lat, colour=rank(desc(pop)))) +
  scale_colour_gradient(low="#c0c030", high="#607848") +
  geom_abline(slope=1, intercept=0) + geom_point(alpha=0.1) +
  theme(aspect.ratio=1, legend.position="none")
grid.arrange(p1, p2, ncol=2)

```

Map of Australian SA2 areas coloured by population.

```{r}
ggplot(sa2_tidy) +
  geom_polygon(aes(x=long, y=lat, group=group,
               fill=population), alpha=0.75)+
  scale_fill_gradient(low = "#d8c0a8", high = "#a86030") +
  theme_map()
```

Map of Australian SA2 areas represented by hexagons, coloured by population.

```{r}
(ausHex <- ggplot(sa2_tidy) +
  geom_polygon(aes(x=long, y=lat, group=group),
               fill="white", colour="grey90") +
  geom_hex(data=sa2_hex, aes(x = hex_long, y = hex_lat,
                             fill = pop, label=name),
         stat = "identity", colour = NA, alpha = 0.75) +
  scale_fill_gradient(low = "#d8c0a8", high = "#a86030") +
  theme_map()
)

library(plotly)
ggplotly(ausHex)
```

