---
title: "Experiment"
author: "Stephanie Kobakian and Di Cook"
date: "5/26/2018"
output: pdf_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, 
                      message=FALSE, 
                      error=FALSE, 
                      warning = FALSE,
                      cache=FALSE, dpi=300, dev ="png")
```

# Null Plots

```{r}
# Load libraries and data sets
library(tidyverse)
library(ggpolypath)
library(ggthemes)
library(gridExtra)
# Tidy format spatial polypaths, for easy plotting
load("data/sa2_tidy11.Rda")
# Hex gridded sa2 regions
load("data/sa2_hex11.Rda")
# Melanoma data not available on github
melanoma_aus <- read_csv("data/melanoma_people_aus.csv")
```

```{r}
# Data manipulation
# Allocate colours
nac_colours <- c("A" = "#33809d",
                 "B" = "#aec6c7",
                 "C" = "#fff4bc",
                 "D" = "#ff9a64",
                 "E" = "#ff3500")

# Join melanoma and hexagon data
sa2_mel <- left_join(sa2_hex, melanoma_aus, by = c("name"= "sa2name"))

sa2_mel <- sa2_mel %>% 
  mutate(colrs = case_when(
      sir_p50 < 0.5  ~ "A",
      sir_p50 >= 0.5 & sir_p50 < 1  ~ "B",
      sir_p50 >= 1 & sir_p50 < 1.5  ~ "C",
      sir_p50 >= 1.5 & sir_p50 < 2  ~ "D",
      sir_p50 > 2  ~ "E")) %>% 
  mutate(s1 = base::sample(colrs, replace=T),
         s2 = base::sample(colrs, replace=T),
         s3 = base::sample(colrs, replace=T))


# group data for mapping
sa2_grouped <- split(sa2_mel, sa2_mel$SUA_NAME_2011)

sa2_grouped <-  plyr::ldply(sa2_grouped, function(x) {
  x %>% as.tibble %>% dplyr::mutate(g_s1 = sample(colrs),
                                    g_s2 = sample(colrs),
                                    g_s3 = sample(colrs))
  })

# data for mapping
map_data <- left_join(sa2_tidy, 
                      dplyr::select(sa2_grouped, SA2_NAME11, hex_long:g_s3), by = c("SA2_NAME11"))
```
 

Map of Australian SA2 areas represented by hexagons, coloured by National Cancer Atlas colours, random generation.

```{r, dpi=500, dev="png"}
#hex_data <- sa2_mel %>% left_join(., sa2_mel)

hexbase <- ggplot(sa2_tidy) +
  geom_polypath(aes(x=long, y=lat, group=group),
               fill="white", colour="grey90") +
    scale_fill_manual(values = nac_colours)+
  theme_map() + 
  guides(fill=FALSE)

h1 <- hexbase + geom_hex(data=sa2_mel,
           aes(x = hex_long, y = hex_lat,
               fill = s1),
         stat = "identity")
h2 <- hexbase + geom_hex(data=sa2_mel,
           aes(x = hex_long, y = hex_lat,
               fill = colrs),
         stat = "identity")
h3 <- hexbase + geom_hex(data=sa2_mel,
           aes(x = hex_long, y = hex_lat,
               fill = s2),
         stat = "identity")
h4 <- hexbase + geom_hex(data=sa2_mel,
           aes(x = hex_long, y = hex_lat,
               fill = s3),
         stat = "identity")

grid.arrange(h1,h2, h3,h4,nrow=2)
```


```{r, dpi=300, dev="png"}
                         
mapbase <- ggplot(map_data) +
  scale_fill_manual(values = nac_colours) +
  theme_map() + 
  guides(fill=FALSE)

m1 <- mapbase + geom_polypath(data=map_data,
                                aes(x=long, y=lat, group=group, fill= s1))
m2 <- mapbase + geom_polypath(data=map_data,
                                aes(x=long, y=lat, group=group, fill= s2))
m3 <- mapbase + geom_polypath(data=map_data,
                                aes(x=long, y=lat, group=group, fill= colrs))
m4 <- mapbase + geom_polypath(data=map_data,
                                aes(x=long, y=lat, group=group, fill= s3))

grid.arrange(m1,m2, m3,m4,nrow=2)
```


# KNN Plots

Map of Australian SA2 areas represented by hexagons, coloured by National Cancer Atlas colours, values randomly sampled from SUA areas.

```{r, dpi=500, dev="png"}
hexbase <- ggplot(sa2_tidy) +
  geom_polypath(aes(x=long, y=lat, group=group),
               fill="white", colour="grey90") +
    scale_fill_manual(values = nac_colours)+
  theme_map() + 
  guides(fill=FALSE)

h1 <- hexbase + geom_hex(data=sa2_grouped,
           aes(x = hex_long, y = hex_lat,
               fill = g_s1),
         stat = "identity")
h2 <- hexbase + geom_hex(data=sa2_grouped,
           aes(x = hex_long, y = hex_lat,
               fill = colrs),
         stat = "identity")
h3 <- hexbase + geom_hex(data=sa2_grouped,
           aes(x = hex_long, y = hex_lat,
               fill = g_s2),
         stat = "identity")
h4 <- hexbase + geom_hex(data=sa2_grouped,
           aes(x = hex_long, y = hex_lat,
               fill = g_s3),
         stat = "identity")

grid.arrange(h1,h2, h3,h4,nrow=2)
```

```{r dpi=300, dev="png"}
mapbase <- ggplot(map_data) +
  scale_fill_manual(values = nac_colours) +
  theme_map() + 
  guides(fill=FALSE)

m1 <- mapbase + geom_polypath(data=map_data,
                                aes(x=long, y=lat, group=group, fill = g_s1))
m2 <- mapbase + geom_polypath(data=map_data,
                                aes(x=long, y=lat, group=group, fill = g_s2))
m3 <- mapbase + geom_polypath(data=map_data,
                                aes(x=long, y=lat, group=group, fill = colrs))
m4 <- mapbase + geom_polypath(data=map_data,
                                aes(x=long, y=lat, group=group, fill = g_s3))

grid.arrange(m1,m2, m3,m4,nrow=2)
```